### ISSUE TITLE
Notation mistake

### ISSUE THREAD

**Issue by seyma-tas** [learn-co-curriculum/dsc-computational-complexity#2]
If  𝑋  is an  (𝑛×𝑘)  matrix:

(𝑋𝑇𝑋)  takes  𝑂(𝑛∗𝑘2)  time and produces a  (𝑘×𝑘)  matrix
The matrix inversion of a (k x k) matrix takes  𝑂(𝑘3)  time
(𝑋𝑇𝑌)  takes  𝑂(𝑛∗𝑘2)  time and produces a  (𝑘×𝑘)  matrix
The final matrix multiplication of two  (𝑘×𝑘)  matrices takes  𝑂(𝑘3)  time
** So the Big O running time for OLS is  𝑂(𝑘2∗(𝑛+𝑘))  - which is pretty expensive **

![image](https://user-images.githubusercontent.com/56923862/81130002-d0e06300-8f0b-11ea-89a5-4129bdaa8a93.png)

**Comment by hoffm386** [comment]
@gadamico I'm not sure that I understand what this issue is saying/suggesting

The current Markdown content is:

```
If $\boldsymbol{X}$ is an $(n \times k)$ matrix:

- $(\boldsymbol{X}^T\boldsymbol{X})$ takes $O(n*k^2)$ time and produces a $(k \times k)$ matrix
- The matrix inversion of a (k x k) matrix takes $O(k^3)$ time
- $(\boldsymbol{X}^T\boldsymbol{Y})$ takes $O(n*k^2)$ time and produces a $(k \times k)$ matrix
- The final matrix multiplication of two $(k \times k)$ matrices takes $O(k^3)$ time

** So the Big O running time for OLS is $O(k^{2*(n + k)})$ - which is pretty expensive **
```

Which renders like this:

![Screen Shot 2022-07-01 at 3 56 44 PM](https://user-images.githubusercontent.com/2507951/176961055-eb6c7836-9d6b-4823-bd79-6033ab780df9.png)
