### ISSUE TITLE
Inactive Link

### ISSUE THREAD

**Issue by shawnjohnsamuel** [learn-co-curriculum/dsc-computational-complexity#3]
The article "Gradient descent in a nutshell" at the end of the lessons seems to be inactive.

**Comment by hoffm386** [comment]
Thanks for flagging! It looks like the author deleted that Medium post so it has been removed from the lesson as part of this commit: https://github.com/learn-co-curriculum/dsc-computational-complexity/commit/d84c05cbc6c9f3b62788b0f81d428673173b580a
